# Generated by Django 4.2.2 on 2023-06-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='publisher_name',
            field=models.CharField(max_length=250),
        ),
    ]
